### ISSUE TITLE
gsc no longer working for google scholar profile

### ISSUE THREAD

**Issue by andrehofmeyr** [TonyWu20/alfred-google-scholar#1]
Hi Tony

Thanks so much for writing this Alfred workflow, which I use all of the time.

Recently, I've noticed that when I search an author name, the first hit produces a "strange" result and doesn't let me access the google scholar profile for the academic for whom I searched. Using myself as an example, this is what I get:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/66821142/214611392-0854983b-68da-44dd-80a5-19d3ca4c6cf5.png">

I don't remember having this issue in the past.

If you can find a fix for it, that would be greatly appreciated.

Cheers,
Andre

**Comment by TonyWu20** [comment]
Hi Andre, I ran a few tests and found it is because the python script chops the google domain prefix, leaving the url beginning with `/citations?...`. I will check this issue when I am free.

**Comment by TonyWu20** [comment]
Hi Andre, I tried a quick fix for it. You can find it in the branch `scholar_profile_fix` and try it. I triggered the bot detection of google so I can't further test it for the next few hours.

**Comment by andrehofmeyr** [comment]
Hi Tony

Many thanks for getting back to me. It seems to be working perfectly now.

Thank you!
